name: Lighthouse Audit

on:
  push:
    branches:
      - main

jobs:

  lighthouse:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v11

        with:
          urls: |
            https://jobboardappl.netlify.app/

          uploadArtifacts: true
          temporaryPublicStorage: true